import Peterson.EconomicalSolutions.Algorithm1

/-! Generated by scripts/economical_solutions_safety.py. The table proposes an
inductive set of 421 states; kernel proofs below must validate it against the
handwritten Lean transitions. No exploration result is assumed as a theorem. -/
namespace EconomicalSolutions.Algorithm1

/-- Ordinal used only to index the certificate; not protocol state. -/
def pcIndex : PC → Nat
  | .down => 0
  | .idle => 1
  | .read1 => 2
  | .write1 .O => 3
  | .write1 .T => 4
  | .write1 .F => 5
  | .read2 => 6
  | .self2 => 7
  | .write2 .O => 8
  | .write2 .T => 9
  | .write2 .F => 10
  | .waitPeer => 11
  | .waitSelf .O => 12
  | .waitSelf .T => 13
  | .waitSelf .F => 14
  | .enter => 15
  | .cs => 16
  | .release => 17

def valueIndex : Value → Nat | .O => 0 | .T => 1 | .F => 2

def localIndex (l : Local) : Nat := 3 * pcIndex l.pc + valueIndex l.q

/-- For each P0 local state, bits name allowed P1 local states. -/
def allowedPeers : Local → Nat
  | ⟨.down, .O⟩ => 15440500590415945
  | ⟨.down, .T⟩ => 0
  | ⟨.down, .F⟩ => 0
  | ⟨.idle, .O⟩ => 15440500590415945
  | ⟨.idle, .T⟩ => 0
  | ⟨.idle, .F⟩ => 0
  | ⟨.read1, .O⟩ => 15440500590415945
  | ⟨.read1, .T⟩ => 0
  | ⟨.read1, .F⟩ => 0
  | ⟨.write1 .O, .O⟩ => 0
  | ⟨.write1 .O, .T⟩ => 0
  | ⟨.write1 .O, .F⟩ => 0
  | ⟨.write1 .T, .O⟩ => 15420708844245065
  | ⟨.write1 .T, .T⟩ => 0
  | ⟨.write1 .T, .F⟩ => 0
  | ⟨.write1 .F, .O⟩ => 15430602838249545
  | ⟨.write1 .F, .T⟩ => 0
  | ⟨.write1 .F, .F⟩ => 0
  | ⟨.read2, .O⟩ => 0
  | ⟨.read2, .T⟩ => 15422907867500617
  | ⟨.read2, .F⟩ => 15439398931271753
  | ⟨.self2, .O⟩ => 0
  | ⟨.self2, .T⟩ => 2239827054665
  | ⟨.self2, .F⟩ => 8813541855305
  | ⟨.write2 .O, .O⟩ => 0
  | ⟨.write2 .O, .T⟩ => 0
  | ⟨.write2 .O, .F⟩ => 0
  | ⟨.write2 .T, .O⟩ => 0
  | ⟨.write2 .T, .T⟩ => 5149071209173065
  | ⟨.write2 .T, .F⟩ => 5145731871019081
  | ⟨.write2 .F, .O⟩ => 0
  | ⟨.write2 .F, .T⟩ => 10276074337370185
  | ⟨.write2 .F, .F⟩ => 10302480602107977
  | ⟨.waitPeer, .O⟩ => 0
  | ⟨.waitPeer, .T⟩ => 5149071209173065
  | ⟨.waitPeer, .F⟩ => 10302480602140745
  | ⟨.waitSelf .O, .O⟩ => 0
  | ⟨.waitSelf .O, .T⟩ => 2239827054665
  | ⟨.waitSelf .O, .F⟩ => 8814079807561
  | ⟨.waitSelf .T, .O⟩ => 0
  | ⟨.waitSelf .T, .T⟩ => 5149071209168969
  | ⟨.waitSelf .T, .F⟩ => 8813541855305
  | ⟨.waitSelf .F, .O⟩ => 0
  | ⟨.waitSelf .F, .T⟩ => 2237679042633
  | ⟨.waitSelf .F, .F⟩ => 10302480602107977
  | ⟨.enter, .O⟩ => 0
  | ⟨.enter, .T⟩ => 2239827054665
  | ⟨.enter, .F⟩ => 8814079807561
  | ⟨.cs, .O⟩ => 0
  | ⟨.cs, .T⟩ => 2239827054665
  | ⟨.cs, .F⟩ => 8814079807561
  | ⟨.release, .O⟩ => 0
  | ⟨.release, .T⟩ => 2239827054665
  | ⟨.release, .F⟩ => 8814079807561

def invariantB (s : State) : Bool := (allowedPeers s.p0).testBit (localIndex s.p1)
def Invariant (s : State) : Prop := invariantB s = true

def allValues : List Value := [.O, .T, .F]
def allPCs : List PC := [.down, .idle, .read1, .write1 .O, .write1 .T, .write1 .F, .read2, .self2, .write2 .O, .write2 .T, .write2 .F, .waitPeer, .waitSelf .O, .waitSelf .T, .waitSelf .F, .enter, .cs, .release]
def allLocals : List Local := allPCs.flatMap fun pc => allValues.map fun q => ⟨pc, q⟩
def allCommands : List Command :=
  [.run false, .run true, .fail false, .fail true, .restart false, .restart true, .stutter]

/-- The checker demands safety and closure at every certified state; none is
excluded on the basis of a Python reachability calculation. -/
def checkState (s : State) : Bool := !invariantB s ||
  (!(s.p0.pc == .cs && s.p1.pc == .cs) && allCommands.all fun c =>
    match next s c with | none => true | some t => invariantB t)

def checkRow (a : Local) : Bool := allLocals.all fun b => checkState ⟨a, b⟩

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
/-- Lean's kernel, not native evaluation, checks the finite inductive certificate. -/
theorem certificate_checked : allLocals.all checkRow = true := by decide +kernel

end EconomicalSolutions.Algorithm1
