import Peterson.EconomicalSolutions.Algorithm2Node

/-! Generated by scripts/economical_solutions_node.py. The table proposes an
inductive set of 261 states; kernel proofs below must validate it against the
handwritten Lean transitions. No exploration result is assumed as a theorem. -/
namespace EconomicalSolutions.Algorithm2.Node

/-- Ordinal used only to index the certificate; not protocol state. -/
def pcIndex : PC → Nat
  | .read1 => 0
  | .write1 .O => 1
  | .write1 .T => 2
  | .write1 .F => 3
  | .write1 .H => 4
  | .read2 => 5
  | .self2 => 6
  | .write2 .O => 7
  | .write2 .T => 8
  | .write2 .F => 9
  | .write2 .H => 10
  | .waitPeer => 11
  | .waitSelf .O => 12
  | .waitSelf .T => 13
  | .waitSelf .F => 14
  | .waitSelf .H => 15
  | .held => 16

def valueIndex : Value → Nat | .O => 0 | .T => 1 | .F => 2 | .H => 3

def localIndex (l : Local) : Nat := 4 * pcIndex l.pc + valueIndex l.q

/-- For each P0 local state, bits name allowed P1 local states. -/
def allowedPeers : Local → Nat
  | ⟨.read1, .O⟩ => 258713890185235403009
  | ⟨.read1, .T⟩ => 0
  | ⟨.read1, .F⟩ => 0
  | ⟨.read1, .H⟩ => 0
  | ⟨.write1 .O, .O⟩ => 0
  | ⟨.write1 .O, .T⟩ => 0
  | ⟨.write1 .O, .F⟩ => 0
  | ⟨.write1 .O, .H⟩ => 0
  | ⟨.write1 .T, .O⟩ => 258407645393394340097
  | ⟨.write1 .T, .T⟩ => 0
  | ⟨.write1 .T, .F⟩ => 0
  | ⟨.write1 .T, .H⟩ => 0
  | ⟨.write1 .F, .O⟩ => 258560767660465848577
  | ⟨.write1 .F, .T⟩ => 0
  | ⟨.write1 .F, .F⟩ => 0
  | ⟨.write1 .F, .H⟩ => 0
  | ⟨.write1 .H, .O⟩ => 0
  | ⟨.write1 .H, .T⟩ => 0
  | ⟨.write1 .H, .F⟩ => 0
  | ⟨.write1 .H, .H⟩ => 0
  | ⟨.read2, .O⟩ => 0
  | ⟨.read2, .T⟩ => 258425659791903822081
  | ⟨.read2, .F⟩ => 258704882848541704449
  | ⟨.read2, .H⟩ => 0
  | ⟨.self2, .O⟩ => 0
  | ⟨.self2, .T⟩ => 147592037769253228801
  | ⟨.self2, .F⟩ => 147718102970716389633
  | ⟨.self2, .H⟩ => 0
  | ⟨.write2 .O, .O⟩ => 0
  | ⟨.write2 .O, .T⟩ => 0
  | ⟨.write2 .O, .F⟩ => 0
  | ⟨.write2 .O, .H⟩ => 0
  | ⟨.write2 .T, .O⟩ => 0
  | ⟨.write2 .T, .T⟩ => 184638683496998506753
  | ⟨.write2 .T, .F⟩ => 184611591118169047297
  | ⟨.write2 .T, .H⟩ => 0
  | ⟨.write2 .F, .O⟩ => 0
  | ⟨.write2 .F, .T⟩ => 221379013926717493249
  | ⟨.write2 .F, .F⟩ => 221811394701089046785
  | ⟨.write2 .F, .H⟩ => 0
  | ⟨.write2 .H, .O⟩ => 0
  | ⟨.write2 .H, .T⟩ => 0
  | ⟨.write2 .H, .F⟩ => 0
  | ⟨.write2 .H, .H⟩ => 0
  | ⟨.waitPeer, .O⟩ => 0
  | ⟨.waitPeer, .T⟩ => 184638683496998506753
  | ⟨.waitPeer, .F⟩ => 221811394701089050881
  | ⟨.waitPeer, .H⟩ => 0
  | ⟨.waitSelf .O, .O⟩ => 0
  | ⟨.waitSelf .O, .T⟩ => 0
  | ⟨.waitSelf .O, .F⟩ => 0
  | ⟨.waitSelf .O, .H⟩ => 0
  | ⟨.waitSelf .T, .O⟩ => 0
  | ⟨.waitSelf .T, .T⟩ => 184638683496998506497
  | ⟨.waitSelf .T, .F⟩ => 144150381039976705
  | ⟨.waitSelf .T, .H⟩ => 0
  | ⟨.waitSelf .F, .O⟩ => 0
  | ⟨.waitSelf .F, .T⟩ => 18085042135764993
  | ⟨.waitSelf .F, .F⟩ => 221811394701089046785
  | ⟨.waitSelf .F, .H⟩ => 0
  | ⟨.waitSelf .H, .O⟩ => 0
  | ⟨.waitSelf .H, .T⟩ => 0
  | ⟨.waitSelf .H, .F⟩ => 0
  | ⟨.waitSelf .H, .H⟩ => 0
  | ⟨.held, .O⟩ => 0
  | ⟨.held, .T⟩ => 18085179576815873
  | ⟨.held, .F⟩ => 144150398224044289
  | ⟨.held, .H⟩ => 162235577895227649

def invariantB (s : State) : Bool := (allowedPeers s.p0).testBit (localIndex s.p1)
def Invariant (s : State) : Prop := invariantB s = true

def allValues : List Value := [.O, .T, .F, .H]
def allPCs : List PC := [.read1, .write1 .O, .write1 .T, .write1 .F, .write1 .H, .read2, .self2, .write2 .O, .write2 .T, .write2 .F, .write2 .H, .waitPeer, .waitSelf .O, .waitSelf .T, .waitSelf .F, .waitSelf .H, .held]
def allLocals : List Local := allPCs.flatMap fun pc => allValues.map fun q => ⟨pc, q⟩
def allCommands : List Command :=
  [.run false, .run true, .reset false, .reset true, .stutter]

/-- The checker demands safety and closure at every certified state; none is
excluded on the basis of a Python reachability calculation. -/
def checkState (s : State) : Bool := !invariantB s ||
  (!(s.p0.pc == .held && s.p1.pc == .held) && allCommands.all fun c =>
    invariantB (next s c))

def checkRow (a : Local) : Bool := allLocals.all fun b => checkState ⟨a, b⟩

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
/-- Lean's kernel, not native evaluation, checks the finite inductive certificate. -/
theorem certificate_checked : allLocals.all checkRow = true := by decide +kernel

end EconomicalSolutions.Algorithm2.Node
