import Peterson.EconomicalSolutions.Algorithm3
import Mathlib.Data.Fin.VecNotation

/-! Generated by experiments/generate_economical_clock_certificate.py.
These complete states and commands are untrusted DATA. The counterexample
module checks them with kernel-reduced `decide`, never native evaluation. -/
namespace EconomicalSolutions.Algorithm3.Counterexample

def stemState (k : Fin 32) : State 4 :=
  match k.val with
  | 0 => ![⟨none, .idle⟩, ⟨none, .idle⟩, ⟨none, .idle⟩, ⟨none, .idle⟩]
  | 1 => ![⟨none, .idle⟩, ⟨none, .joinLower 0⟩, ⟨none, .idle⟩, ⟨none, .idle⟩]
  | 2 => ![⟨none, .idle⟩, ⟨none, .joinUpper 3⟩, ⟨none, .idle⟩, ⟨none, .idle⟩]
  | 3 => ![⟨none, .idle⟩, ⟨none, .joinUpper 2⟩, ⟨none, .idle⟩, ⟨none, .idle⟩]
  | 4 => ![⟨none, .idle⟩, ⟨none, .joinWrite false⟩, ⟨none, .idle⟩, ⟨none, .idle⟩]
  | 5 => ![⟨none, .idle⟩, ⟨(some false), .attempt⟩, ⟨none, .idle⟩, ⟨none, .idle⟩]
  | 6 => ![⟨none, .idle⟩, ⟨(some false), .attempt⟩, ⟨none, .idle⟩, ⟨none, .joinLower 2⟩]
  | 7 => ![⟨none, .idle⟩, ⟨(some false), .attempt⟩, ⟨none, .idle⟩, ⟨none, .joinLower 1⟩]
  | 8 => ![⟨none, .idle⟩, ⟨(some false), .attempt⟩, ⟨none, .idle⟩, ⟨none, .joinWrite false⟩]
  | 9 => ![⟨none, .idle⟩, ⟨(some false), .attempt⟩, ⟨none, .joinLower 1⟩, ⟨none, .joinWrite false⟩]
  | 10 => ![⟨none, .idle⟩, ⟨(some false), .attempt⟩, ⟨none, .joinWrite false⟩, ⟨none, .joinWrite false⟩]
  | 11 => ![⟨none, .idle⟩, ⟨(some false), .attempt⟩, ⟨(some false), .attempt⟩, ⟨none, .joinWrite false⟩]
  | 12 => ![⟨none, .idle⟩, ⟨(some false), .tickLower 0 false⟩, ⟨(some false), .attempt⟩, ⟨none, .joinWrite false⟩]
  | 13 => ![⟨none, .idle⟩, ⟨(some false), .tickUpper 3⟩, ⟨(some false), .attempt⟩, ⟨none, .joinWrite false⟩]
  | 14 => ![⟨none, .idle⟩, ⟨(some false), .tickUpper 2⟩, ⟨(some false), .attempt⟩, ⟨none, .joinWrite false⟩]
  | 15 => ![⟨none, .idle⟩, ⟨(some false), .upperOwn 2 false⟩, ⟨(some false), .attempt⟩, ⟨none, .joinWrite false⟩]
  | 16 => ![⟨none, .idle⟩, ⟨(some false), .tickRead⟩, ⟨(some false), .attempt⟩, ⟨none, .joinWrite false⟩]
  | 17 => ![⟨none, .idle⟩, ⟨(some false), .tickWrite true⟩, ⟨(some false), .attempt⟩, ⟨none, .joinWrite false⟩]
  | 18 => ![⟨none, .idle⟩, ⟨(some true), .attempt⟩, ⟨(some false), .attempt⟩, ⟨none, .joinWrite false⟩]
  | 19 => ![⟨none, .idle⟩, ⟨(some true), .attempt⟩, ⟨(some false), .tickLower 1 false⟩, ⟨none, .joinWrite false⟩]
  | 20 => ![⟨none, .idle⟩, ⟨(some true), .attempt⟩, ⟨(some false), .lowerOwn 1 true⟩, ⟨none, .joinWrite false⟩]
  | 21 => ![⟨none, .idle⟩, ⟨(some true), .attempt⟩, ⟨(some false), .tickLower 0 true⟩, ⟨none, .joinWrite false⟩]
  | 22 => ![⟨none, .idle⟩, ⟨(some true), .attempt⟩, ⟨(some false), .tickRead⟩, ⟨none, .joinWrite false⟩]
  | 23 => ![⟨none, .idle⟩, ⟨(some true), .attempt⟩, ⟨(some false), .tickWrite true⟩, ⟨none, .joinWrite false⟩]
  | 24 => ![⟨none, .idle⟩, ⟨(some true), .attempt⟩, ⟨(some true), .attempt⟩, ⟨none, .joinWrite false⟩]
  | 25 => ![⟨none, .idle⟩, ⟨(some true), .tickLower 0 false⟩, ⟨(some true), .attempt⟩, ⟨none, .joinWrite false⟩]
  | 26 => ![⟨none, .idle⟩, ⟨(some true), .tickUpper 3⟩, ⟨(some true), .attempt⟩, ⟨none, .joinWrite false⟩]
  | 27 => ![⟨none, .idle⟩, ⟨(some true), .tickUpper 2⟩, ⟨(some true), .attempt⟩, ⟨none, .joinWrite false⟩]
  | 28 => ![⟨none, .idle⟩, ⟨(some true), .upperOwn 2 true⟩, ⟨(some true), .attempt⟩, ⟨none, .joinWrite false⟩]
  | 29 => ![⟨none, .idle⟩, ⟨(some true), .tickRead⟩, ⟨(some true), .attempt⟩, ⟨none, .joinWrite false⟩]
  | 30 => ![⟨none, .idle⟩, ⟨(some true), .tickWrite false⟩, ⟨(some true), .attempt⟩, ⟨none, .joinWrite false⟩]
  | _ => ![⟨none, .idle⟩, ⟨(some false), .attempt⟩, ⟨(some true), .attempt⟩, ⟨none, .joinWrite false⟩]

def stemCommand (k : Fin 32) : Command 4 :=
  match k.val with
  | 0 => .start 1
  | 1 => .run 1
  | 2 => .run 1
  | 3 => .run 1
  | 4 => .run 1
  | 5 => .start 3
  | 6 => .run 3
  | 7 => .run 3
  | 8 => .start 2
  | 9 => .run 2
  | 10 => .run 2
  | 11 => .run 1
  | 12 => .run 1
  | 13 => .run 1
  | 14 => .run 1
  | 15 => .run 1
  | 16 => .run 1
  | 17 => .run 1
  | 18 => .run 2
  | 19 => .run 2
  | 20 => .run 2
  | 21 => .run 2
  | 22 => .run 2
  | 23 => .run 2
  | 24 => .run 1
  | 25 => .run 1
  | 26 => .run 1
  | 27 => .run 1
  | 28 => .run 1
  | 29 => .run 1
  | 30 => .run 1
  | _ => .run 3

def cycleState (k : Fin 21) : State 4 :=
  match k.val with
  | 0 => ![⟨none, .idle⟩, ⟨(some false), .attempt⟩, ⟨(some true), .attempt⟩, ⟨(some false), .attempt⟩]
  | 1 => ![⟨none, .joinUpper 3⟩, ⟨(some false), .attempt⟩, ⟨(some true), .attempt⟩, ⟨(some false), .attempt⟩]
  | 2 => ![⟨none, .joinWrite true⟩, ⟨(some false), .attempt⟩, ⟨(some true), .attempt⟩, ⟨(some false), .attempt⟩]
  | 3 => ![⟨(some true), .attempt⟩, ⟨(some false), .attempt⟩, ⟨(some true), .attempt⟩, ⟨(some false), .attempt⟩]
  | 4 => ![⟨(some true), .attempt⟩, ⟨(some false), .attempt⟩, ⟨(some true), .tickLower 1 false⟩, ⟨(some false), .attempt⟩]
  | 5 => ![⟨(some true), .attempt⟩, ⟨(some false), .attempt⟩, ⟨(some true), .lowerOwn 1 false⟩, ⟨(some false), .attempt⟩]
  | 6 => ![⟨(some true), .attempt⟩, ⟨(some false), .attempt⟩, ⟨(some true), .tickLower 0 true⟩, ⟨(some false), .attempt⟩]
  | 7 => ![⟨(some true), .attempt⟩, ⟨(some false), .attempt⟩, ⟨(some true), .lowerOwn 0 true⟩, ⟨(some false), .attempt⟩]
  | 8 => ![⟨(some true), .attempt⟩, ⟨(some false), .attempt⟩, ⟨(some true), .attempt⟩, ⟨(some false), .attempt⟩]
  | 9 => ![⟨(some true), .attempt⟩, ⟨(some false), .attempt⟩, ⟨(some true), .attempt⟩, ⟨(some false), .tickLower 2 false⟩]
  | 10 => ![⟨(some true), .attempt⟩, ⟨(some false), .attempt⟩, ⟨(some true), .attempt⟩, ⟨(some false), .lowerOwn 2 true⟩]
  | 11 => ![⟨(some true), .attempt⟩, ⟨(some false), .attempt⟩, ⟨(some true), .attempt⟩, ⟨(some false), .tickLower 1 true⟩]
  | 12 => ![⟨(some true), .attempt⟩, ⟨(some false), .attempt⟩, ⟨(some true), .attempt⟩, ⟨(some false), .lowerOwn 1 false⟩]
  | 13 => ![⟨(some true), .attempt⟩, ⟨(some false), .attempt⟩, ⟨(some true), .attempt⟩, ⟨(some false), .attempt⟩]
  | 14 => ![⟨none, .down⟩, ⟨(some false), .attempt⟩, ⟨(some true), .attempt⟩, ⟨(some false), .attempt⟩]
  | 15 => ![⟨none, .idle⟩, ⟨(some false), .attempt⟩, ⟨(some true), .attempt⟩, ⟨(some false), .attempt⟩]
  | 16 => ![⟨none, .idle⟩, ⟨(some false), .tickLower 0 false⟩, ⟨(some true), .attempt⟩, ⟨(some false), .attempt⟩]
  | 17 => ![⟨none, .idle⟩, ⟨(some false), .tickUpper 3⟩, ⟨(some true), .attempt⟩, ⟨(some false), .attempt⟩]
  | 18 => ![⟨none, .idle⟩, ⟨(some false), .upperOwn 3 false⟩, ⟨(some true), .attempt⟩, ⟨(some false), .attempt⟩]
  | 19 => ![⟨none, .idle⟩, ⟨(some false), .tickUpper 2⟩, ⟨(some true), .attempt⟩, ⟨(some false), .attempt⟩]
  | _ => ![⟨none, .idle⟩, ⟨(some false), .upperOwn 2 true⟩, ⟨(some true), .attempt⟩, ⟨(some false), .attempt⟩]

def cycleCommand (k : Fin 21) : Command 4 :=
  match k.val with
  | 0 => .start 0
  | 1 => .run 0
  | 2 => .run 0
  | 3 => .run 2
  | 4 => .run 2
  | 5 => .run 2
  | 6 => .run 2
  | 7 => .run 2
  | 8 => .run 3
  | 9 => .run 3
  | 10 => .run 3
  | 11 => .run 3
  | 12 => .run 3
  | 13 => .fail 0
  | 14 => .restart 0
  | 15 => .run 1
  | 16 => .run 1
  | 17 => .run 1
  | 18 => .run 1
  | 19 => .run 1
  | _ => .run 1

end EconomicalSolutions.Algorithm3.Counterexample
